import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Introduction from '@/components/Introduction'
import Education from '@/components/Education'
import Experience from '@/components/Experience'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Nav from '@/components/Nav'
import Wireframe from '@/components/Wireframe'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white absolute w-full h-full top-0 left-0'>
        <Nav/>
        {/* <div className='w-full mt-14'></div> */}
        <Introduction/>
        {/* <Wireframe/> */}
        {/* <Education/>
        <Experience/>
        <Projects/>
        <Contact/> */}
      </main>
      
    </>
  )
}
