import Background from '@/components/Background'
import Contact from '@/components/Contact'
import MenuContainer from '@/components/MenuContainer'
import Overlay from '@/components/Overlay'
import ThreeCanvas from '@/components/ThreeCanvas'
import { MyStoreContext } from '@/store/mystore'
import Head from 'next/head'
import { useContext } from 'react'

export default function Home() {
  const { state } = useContext(MyStoreContext);
  const { menuOpen } = state
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`absolute w-full min-h-full top-0 left-0 ${menuOpen && 'overflow-hidden'} bg-background text-text-muted`}>
        <div className='relative w-full min-h-full mx-auto'>
          <ThreeCanvas />
          <MenuContainer />
          <Overlay />
          <Contact />
        </div>

      </main>
    </>
  )
}
