import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Introduction from '@/components/Introduction'
import Education from '@/components/Education'
import Experience from '@/components/Experience'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Nav from '@/components/Brand'
import Wireframe from '@/components/Wireframe'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white absolute w-full h-full top-0 left-0'>
        <Nav />
        {/* <div className='w-full mt-14'></div> */}
        <div className='flex w-full h-full'>
          <Introduction />
          <div className='menu-drawer absolute w-96 h-full -right-96 bg-white flex flex-col justify-center text-3xl gap-5 text-primary font-semibold pl-12'>
            <Link href={"/"} className={`${router.asPath === '/' && 'active'}`}>Home</Link>
            <Link href={"#Education"} className={`${router.asPath === '/#Education' && 'active'}`}>Education</Link>
            <Link href={"#Experience"} className={`${router.asPath === '/#Experience' && 'active'}`}>Experience</Link>
            <Link href={"#Projects"} className={`${router.asPath === '/#Projects' && 'active'}`}>Projects</Link>
            <Link href={"#Contact"} className={`${router.asPath === '/#Contact' && 'active'}`}>Contact</Link>
          </div>
        </div>
        {/* <Wireframe/> */}
        {/* <Education/>
        <Experience/>
        <Projects/>
        <Contact/> */}
      </main>

    </>
  )
}
